(function(){(function(){function ba(){for(var a='',b=0;16>b;b++)a+=ya[Math.round(15*Math.random())];return a}function n(){return(new Date).getTime()}function J(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent('on'+b,c)}function K(a,b){for(var c=0,f=a.length;c<f;c++)if(a[c].test(b))return!0;return!1}function ca(){A.time=n();var a=A.time,b=T[A.name];if(b)for(var c=0,f=b.length;c<f;c++)b[c](a)}function da(a,b){w[a]=b}function U(a){D=a;w[a].I()}function ea(){U('pageLoaded')}function x(a){a.k=
d.H;a.r=d.b;a.p=d.page;a.pl=d.v;a.ui=d.ea;a.un=d.userName;a.ue=d.da;a.ul=fa;a.ph=w[D].A();a.ww=g.innerWidth;a.wh=g.innerHeight;p.connection&&p.connection.effectiveType&&(a.ct=p.connection.effectiveType);B.visibilityState&&(a.h='hidden'===B.visibilityState?1:0);ga(a,d.Y)}function ga(a,b){var c=0,f;for(f in b)if(L.call(b,f)){c++;if(50<c)break;var e=null;if('string'===typeof b[f])e=b[f];else if(void 0===b[f])e='undefined';else if(null===b[f])e='null';else if(g.JSON)try{e=g.JSON.stringify(b[f])}catch(h){continue}else e=
String(b[f]);a['m_'+f]=e.substring(0,256)}}function za(a){var b=[Math.round(a.startTime-d.R),Math.round(a.duration),ha[a.initiatorType]||ha.other];'number'===typeof a.transferSize&&'number'===typeof a.encodedBodySize&&0<a.encodedBodySize?(0===a.transferSize?b.push(V.ja):0<a.transferSize&&(0===a.encodedBodySize||a.transferSize<a.encodedBodySize)?b.push(V.va):b.push(V.na),null!=a.encodedBodySize?b.push(a.encodedBodySize):b.push(''),null!=a.decodedBodySize?b.push(a.decodedBodySize):b.push(''),null!=
a.transferSize?b.push(a.transferSize):b.push('')):(b.push(''),b.push(''),b.push(''),b.push(''));null!=a.responseStart&&a.responseStart>=a.fetchStart&&(b.push(y(a.redirectEnd,a.redirectStart)),b.push(y(a.domainLookupStart,a.fetchStart)),b.push(y(a.domainLookupEnd,a.domainLookupStart)),null!=a.secureConnectionStart&&0<a.secureConnectionStart?(b.push(y(a.secureConnectionStart,a.connectStart)),b.push(y(a.connectEnd,a.secureConnectionStart))):(b.push(y(a.connectEnd,a.connectStart)),b.push('')),b.push(y(a.responseStart,
a.requestStart)),b.push(y(a.responseEnd,a.responseStart)));return b.join(',').replace(/,+$/,'')}function y(a,b){if(null==a||null==b||a===b)return'';var c=Math.round(a-b);return 0>c?'':c}function M(){this.root={}}function W(a){var b=[],c;for(c in a)L.call(a,c)&&b.push(c);return b}function ia(){if(!X)return d.C;var a=k.timing;return a.fetchStart-(a.redirectEnd-a.redirectStart)}function ja(a,b){var c=null;g.chrome&&g.chrome.loadTimes?c=1E3*g.chrome.loadTimes().firstPaintTime:'number'===typeof g.performance.timing.pa?
c=g.performance.timing.pa:'number'===typeof g.performance.timing.ma&&(c=g.performance.timing.ma);null!=c&&0!==c&&(a.t_fp=Math.round(c-b))}function ka(a){(a[d.i]=a[d.i]||{}).g=!0}function la(a){return String(a).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/\t/g,'\\t')}function N(){null!=F&&(clearTimeout(F),F=null);if(0!==O.length){var a;a=O;for(var b='',c=0;c<a.length;c++){var f=a[c],b=b+'\n',e;for(e in f)if(L.call(f,e)){var h=f[e];null!=h&&(b+='\n'+la(e)+'\t'+la(h))}}a=b.substring(2);O.length=
0;0!==a.length&&!1===('function'===typeof p.sendBeacon&&p.sendBeacon(String(d.f),a))&&(b=new l,ka(b),b.open('POST',String(d.f),!0),b.setRequestHeader('Content-type','text/plain;charset=UTF-8'),b.responseType='text',b.timeout=d.M,b.send(a))}}function G(a){var b=a.j||512,c=a.o||32,f=0,e=0;setInterval(function(){e=0},1E4);return function(){return++f>b||++e>c}}function v(a){if(!Aa())try{if(ma&&0<d.w)O.push(a),'visible'===B.visibilityState&&0<d.w?null==F&&(F=setTimeout(N,d.w)):N();else{var b,c='',f;for(f in a)L.call(a,
f)&&null!=a[f]&&(c+='&'+na(f)+'='+na(String(a[f])));b=c.substring(1);if(0!==b.length)if(l&&2E3<b.length){var e=new l;ka(e);e.open('POST',String(d.f),!0);e.setRequestHeader('Content-type','application/x-www-form-urlencoded;charset=UTF-8');e.responseType='text';e.timeout=d.M;e.send(b)}else{var h=String(d.f)+'?'+b;(new Image).src=h}}}catch(m){}}function oa(a){if(!a)return!0;a=String(a);return!a||null==a.substring||'data:'===a.substring(0,5).toLowerCase()||d.T&&Ba.test(a)?!0:K(d.U,a)}function Ca(){var a=
g.onerror;g.onerror=function(b,c,f,e,d){if(P)P=!1;else{var g=d&&d.stack;g||(g='at '+c+' '+f,null!=e&&(g+=':'+e));Y(b,g)}if('function'===typeof a)return a.apply(this,arguments)}}function E(a,b){a&&('string'===typeof a?Y(a,'',b):Y(a.message,a.stack,b))}function Y(a,b,c){if(a&&!(100<pa)&&a&&!K(d.S,a)){20<=Q&&(C={},Q=0);a=String(a).substring(0,300);b=String(b||'').split('\n').slice(0,30).join('\n');var f=g.location.href,e=w[D].B(),h=a+b+f+(e||''),m=C[h];m?m.J++:(m=void 0,c&&c.componentStack&&(m=String(c.componentStack).substring(0,
4096)),C[h]={message:a,stack:b,la:m,location:f,ra:e,J:1,ca:0},Q++);R||(R=setTimeout(Da,1E3))}}function Da(){clearTimeout(R);R=null;for(var a in C)if(C.hasOwnProperty(a)){var b=C[a];if(b.J>b.ca){var c=H(),b={ty:'err',s:c,t:b.ra||c,ts:n(),l:b.location,e:b.message,st:b.stack,cs:b.la,c:b.J-b.ca};x(b);v(b);pa++}}C={};Q=0}function Ea(a){null==a.reason?E({message:'Unhandled promise rejection: <no reason defined>',stack:"<unavailable because Promise wasn't rejected with an Error object>"}):'string'===typeof a.reason.message?
E({message:'Unhandled promise rejection: '+a.reason.message,stack:'string'===typeof a.reason.stack?a.reason.stack:"<unavailable because Promise wasn't rejected with an Error object>"}):'object'!==typeof a.reason&&E({message:'Unhandled promise rejection: '+a.reason,stack:"<unavailable because Promise wasn't rejected with an Error object>"})}function qa(a){if(S)try{S.href=a,a=S.href}catch(b){}4096<a.length&&(a=a.substring(0,4096));return a}function ra(a){if(!z||!t)return!1;try{return z.href=a,(z.protocol&&
':'!==z.protocol?z.protocol:t.protocol)===t.protocol&&(z.hostname||t.hostname)===t.hostname&&(z.port||t.port)===t.port}catch(b){return!1}}function Fa(){if(l&&(new l).addEventListener){var a=l.prototype.open,b=l.prototype.setRequestHeader,c=l.prototype.send;l.prototype.open=function(b,c,h){function f(a){u.g||0!==r.st||(r.st=a,r.d=Math.max(0,n()-(r.ts+d.b)),v(r))}function e(){f(I.timeout)}function k(a){u.g||(a=a&&(a.error&&a.error.message||a.message),'string'===typeof a&&(r.e=a.substring(0,300)),f(I.error))}
function l(){f(I.abort)}function p(){if(4===q.readyState){var a;try{a=q.status}catch(Ua){f(I.error);return}0!==a&&f(a)}}var q=this;if(Ga())return a.apply(q,arguments);var u=q[d.i]=q[d.i]||{};if(u.g)return a.apply(q,arguments);u.g=oa(c);if(u.g)return a.apply(q,arguments);u.F=H();u.aa=ra(c)||K(d.L,c);var r={ty:'xhr',t:u.F,s:u.F,ts:0,d:0,l:g.location.href,m:b,u:qa(c),a:void 0===h||h?1:0,st:0,e:void 0,bc:u.aa?1:0};u.O=r;try{var t=a.apply(q,arguments);q.addEventListener('timeout',e);q.addEventListener('error',
k);q.addEventListener('abort',l);q.addEventListener('readystatechange',p);return t}catch(sa){throw r.ts=n()-d.b,r.st=I.qa,r.e=sa.message,x(r),v(r),q[d.i]=null,sa;}};l.prototype.setRequestHeader=function(a){var c=this[d.i];c&&Ha.test(a)&&(c.g=!0);return b.apply(this,arguments)};l.prototype.send=function(){var a=this[d.i];if(!a||a.g)return c.apply(this,arguments);a.aa&&(b.call(this,'X-INSTANA-T',a.F),b.call(this,'X-INSTANA-S',a.F),b.call(this,'X-INSTANA-L','1'));a.O.ts=n()-d.b;x(a.O);return c.apply(this,
arguments)}}}function Ia(){if(!Z)return null;for(var a=k.getEntriesByType('navigation'),b=0;b<a.length;b++){var c=a[b];if(null!=c.serverTiming)for(var f=0;f<c.serverTiming.length;f++){var e=c.serverTiming[f];if(e.name===d.ta)return e.description}}return null}function Ja(a,b,c){var f=a[d.G]=a[d.G]||[];a=ua(a,c);if(-1!==a)return f[a].ha;f.push({ha:b,wa:c});return b}function ua(a,b){for(var c=a[d.G],f=0;f<c.length;f++){var e;a:if(e=c[f].wa,e.length!==b.length)e=!1;else{for(var g=0;g<e.length;g++)if(e[g]!==
b[g]){e=!1;break a}e=!0}if(e)return f}return-1}function Ka(a){if(a&&'function'===typeof a.prototype.addEventListener&&'function'===typeof a.prototype.removeEventListener){var b=a.prototype.addEventListener,c=a.prototype.removeEventListener;a.prototype.addEventListener=function(a,c,d){if('function'!==typeof c)return b.apply(this,arguments);for(var e=Array(arguments.length),f=0;f<arguments.length;f++)e[f]=arguments[f];e[1]=function(){try{return c.apply(this,arguments)}catch(ta){throw E(ta),P=!0,ta;
}};e[1]=Ja(this,e[1],[a,c,null==d?!1:'object'===typeof d?!!d.ka:!!d]);return b.apply(this,e)};a.prototype.removeEventListener=function(a,b,g){if('function'!==typeof b)return c.apply(this,arguments);for(var f=Array(arguments.length),e=0;e<arguments.length;e++)f[e]=arguments[e];var h=[a,b,null==g?!1:'object'===typeof g?!!g.ka:!!g],e=this[d.G];if(null==e)e=b;else if(h=ua(this,h),-1===h)e=b;else{var k=e[h];e.splice(h,1);e=k.ha}f[1]=e;return c.apply(this,f)}}}function La(a){if(!Ma()){var b={ty:'csp',ts:n(),
l:g.location.href,bu:a.blockedURI,ed:a.effectiveDirective,vd:a.violatedDirective,op:a.originalPolicy,di:a.disposition,st:a.statusCode,sa:a.sample,sf:a.sourceFile};a.lineNumber&&(b.ln=a.lineNumber);a.columnNumber&&(b.cn=a.columnNumber);x(b);v(b)}}function Na(){g.fetch&&g.Request&&(g.fetch=function(a,b){var c=new Request(a,b);if(Oa())return aa(c);var f=c.url;if(oa(f))return aa(c);var e={ty:'xhr',ts:n()-d.b,d:0,l:g.location.href,m:'',u:'',a:1,st:0,e:void 0};x(e);var h=H(),m=ra(f)||K(d.L,f);e.t=h;e.s=
h;e.m=c.method;e.u=qa(f);e.a=1;e.bc=m?1:0;m&&(c.headers.append('X-INSTANA-T',h),c.headers.append('X-INSTANA-S',h),c.headers.append('X-INSTANA-L','1'));return aa(c).then(function(a){e.st=a.status;e.d=n()-(e.ts+d.b);v(e);return a})['catch'](function(a){e.d=n()-(e.ts+d.b);e.e=a.message;e.st=-103;v(e);throw a;})})}function va(a){switch(a[0]){case 'apiKey':d.H=a[1];break;case 'key':d.H=a[1];break;case 'reportingUrl':d.f=a[1];break;case 'meta':d.Y[a[1]]=a[2];break;case 'traceId':d.D=a[1];break;case 'ignoreUrls':d.U=
a[1];break;case 'ignoreErrorMessages':d.S=a[1];break;case 'whitelistedOrigins':d.L=a[1];break;case 'manualPageLoadEvent':d.W=!0;break;case 'triggerPageLoad':d.X=!0;w[D].K();break;case 'xhrTransmissionTimeout':d.M=a[1];break;case 'autoClearResourceTimings':d.N=a[1];break;case 'page':var b=a[1];a=d.page;d.page=b;'pl'===w[D].A()&&null==a||a===b||Pa()||(b={ty:'pc',ts:n(),l:g.location.href},x(b),v(b));break;case 'ignorePings':d.T=a[1];break;case 'reportError':E(a[1],a[2]);break;case 'wrapEventHandlers':d.fa=
a[1];break;case 'wrapTimers':d.ga=a[1];break;case 'getPageLoadId':return d.v;case 'user':a[1]&&(d.ea=String(a[1]).substring(0,128));a[2]&&(d.userName=String(a[2]).substring(0,128));a[3]&&(d.da=String(a[3]).substring(0,128));break;case 'reportEvent':b=a[1];a=a[2];var c=w[D].B(),f=H();c||(c=f);b={ty:'cus',s:f,t:c,ts:n(),n:b,l:g.location.href};x(b);a&&(a.meta&&ga(b,a.meta),'number'===typeof a.duration&&(b.d=a.duration),'string'===typeof a.backendTraceId&&(b.bt=a.backendTraceId.substring(0,64)),a.error&&
(b.e=String(a.error.message).substring(0,300),b.st=String(a.error.stack||'').split('\n').slice(0,30).join('\n')),'string'===typeof a.componentStack&&(b.cs=a.componentStack.substring(0,4096)));v(b);break;case 'beaconBatchingTime':d.w=a[1];break;case 'collectCspViolations':d.P=a[1]}}function wa(a){var b=g[a];'function'===typeof b&&(g[a]=function(a){for(var c=Array(arguments.length),d=0;d<arguments.length;d++)c[d]=arguments[d];c[0]=Qa(a);return b.apply(this,c)})}function Qa(a){return'function'!==typeof a?
a:function(){try{return a.apply(this,arguments)}catch(b){throw E(b),P=!0,b;}}}function Ra(){g[g[d.Z]]=function(){return va(arguments)}}var g=window,B=g.document,p=navigator,na=g.encodeURIComponent,l=g.XMLHttpRequest,aa=g.fetch,L=Object.prototype.hasOwnProperty,ya='0123456789abcdef'.split('');g.crypto&&g.crypto.getRandomValues&&g.Uint32Array&&(ba=function(){var a=new g.Uint32Array(2);g.crypto.getRandomValues(a);return a[0].toString(16)+a[1].toString(16)});var H=ba,T={},A={name:'e:onLoad',time:null,
oa:function(){if('complete'===document.readyState)return ca();J(g,'load',function(){setTimeout(ca,0)})}},w={},D,k=g.performance||g.Aa||g.ya||g.xa,X=k&&k.timing,Z=k&&k.getEntriesByType,d={Z:'InstanaEumObject',v:H(),D:null,ta:'intid',b:n(),R:k&&k.now?k.now():0,C:n(),f:'//eum.instana.io',w:2E3,H:null,Y:{},U:[],T:!0,S:[],M:2E4,L:[],W:!1,X:!1,N:!0,page:void 0,fa:!1,G:'__instanaOriginalFunctions__',ga:!1,i:'__instanaSecretData__',ea:void 0,userName:void 0,da:void 0,P:!1},Sa={I:function(){if(!d.W||d.X){var a=
A.name;(T[a]=T[a]||[]).push(ea);A.oa()}},B:function(){return d.v},A:function(){return'pl'},K:ea},fa;fa=p.languages&&0<p.languages.length?p.languages.slice(0,5).join(','):'string'===typeof p.ua?''+p.ua:void 0;var ha={other:0,img:1,image:1,link:2,script:3,css:4,xmlhttprequest:5,fetch:5,beacon:5,html:6,navigation:6},V={za:0,ja:1,va:2,na:3};M.prototype.ia=function(a,b){this.V(this.root,a.split(''),0,b)};M.prototype.V=function(a,b,c,d){var e=b[c];null==e?(a['<END>']=a['<END>']||[]).push(d):(a=a[e]=a[e]||
{},this.V(a,b,c+1,d))};M.prototype.ba=function(a){a=a||this.root;var b=W(a);if(1===b.length&&'<END>'===b[0])return a['<END>'].slice();for(var c={},d=0,e=b.length;d<e;d++){var g=b[d],m=a[g];if('<END>'===g)c.$=m.slice();else{for(var m=g,g=a[g],k=W(g);1===k.length&&'<END>'!==k[0];)m+=k[0],g=g[k[0]],k=W(g);c[m]=this.ba(g)}}return c};var O=[],F,Ta='string'===typeof B.visibilityState,ma=!!l&&Ta&&'function'===typeof p.sendBeacon;ma&&(J(B,'visibilitychange',function(){'visible'!==B.visibilityState&&N()}),
J(g,'beforeunload',N));var Aa=G({j:1024,o:128}),xa=!1,Ba=/.*\/ping(\/?$|\?.*)/i,pa=0,Q=0,C={},R,P=!1,S=null;try{S=document.createElement('a')}catch(a){}var z=null,t=null;try{z=document.createElement('a'),t=document.createElement('a'),t.href=g.location.href}catch(a){}var Ga=G({j:512,o:32}),I={timeout:-100,abort:-101,qa:-102,error:-103},Ha=/^X-INSTANA-T$/i,Ma=G({j:64,o:32}),Oa=G({j:512,o:32}),Pa=G({j:512,o:32});da('init',{I:function(){var a=g[g[d.Z]];if(a&&a.q&&'number'===typeof a.l){for(var b=a.q,
c=0,f=b.length;c<f;c++)va(b[c]);d.D=d.D||Ia();d.C=a.l;Ra();d.f&&(Fa(),Na(),Ca(),d.ga&&(wa('setTimeout'),wa('setInterval')),d.fa&&Ka(g.EventTarget),'function'===typeof g.addEventListener&&g.addEventListener('unhandledrejection',Ea),d.P&&J(B,'securitypolicyviolation',La),U('waitForPageLoad'))}},B:function(){return d.v},A:function(){return'pl'},K:function(){}});w.waitForPageLoad=Sa;da('pageLoaded',{I:function(){if(!xa){xa=!0;var a={ty:'pl'};x(a);a.t=d.v;a.bt=d.D;a.u=g.location.href;a.ph='pl';if(X){var b=
k.timing,c=b.redirectEnd-b.redirectStart,f=ia();a.ts=f-d.b;0<b.loadEventStart?a.d=b.loadEventStart-b.fetchStart:(a.d=Number(A.time)-d.C,a.tim='0');a.t_unl=b.unloadEventEnd-b.unloadEventStart;a.t_red=c;a.t_apc=b.domainLookupStart-b.fetchStart;a.t_dns=b.domainLookupEnd-b.domainLookupStart;null!=b.secureConnectionStart&&0<b.secureConnectionStart?(a.t_tcp=b.secureConnectionStart-b.connectStart,a.t_ssl=b.connectEnd-b.secureConnectionStart):(a.t_tcp=b.connectEnd-b.connectStart,a.t_ssl=0);a.t_req=b.responseStart-
b.requestStart;a.t_rsp=b.responseEnd-b.responseStart;a.t_dom=b.domContentLoadedEventStart-b.domLoading;a.t_chi=b.loadEventEnd-b.domContentLoadedEventStart;a.t_bac=b.responseStart-f;a.t_fro=b.loadEventEnd-b.responseStart;a.t_pro=b.loadEventStart-b.domLoading;a.t_loa=b.loadEventEnd-b.loadEventStart;if(Z){for(var b=k.getEntriesByType('paint'),c=!1,e=0;e<b.length;e++){var h=b[e];switch(h.name){case 'first-paint':a.t_fp=h.startTime|0;c=!0;break;case 'first-contentful-paint':a.t_fcp=h.startTime|0}}c||ja(a,
f)}else ja(a,f)}else a.ts=ia()-d.b,a.d=Number(A.time)-d.C,X||(a.tim='0');if(Z&&g.JSON){f=k.getEntriesByType('resource');b=new M;c=null!=d.f?d.f.toLowerCase():null;e=0;for(h=f.length;e<h;e++){var m=f[e];if(!(0>m.duration)){var l=m.name,n=l.toLowerCase(),p=m.initiatorType;'about:blank'===n||0===n.indexOf('javascript:')||null!=c&&0===n.indexOf(c)||(255<l.length&&(l=l.substring(0,255)),('xmlhttprequest'!==p||m.startTime<d.R)&&b.ia(l,za(m)))}}f=b.ba();a.res=g.JSON.stringify(f);d.N&&k.clearResourceTimings&&
k.clearResourceTimings()}v(a)}},B:function(){return null},A:function(){},K:function(){}});U('init')})();})();
//# sourceMappingURL=eum.min.js.map
