//tealium universal tag - utag.408 ut4.0.201901101205, Copyright 2019 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1,'link':1};u.initialized=false;u.map={"tag_id":"pixel_id","vk_products_event":"products_event","vk_price_list_id":"price_list_id","vk_parameters":"parameters"};u.extend=[function(a,b){b.tag_id='VK-RTRG-296620-3IQOQ';b.vk_price_list_id='2210';if(a=='view'){b.vk_products_event='view_other';var pageview_events={'HOME':'view_home','PLP':'view_category','CLP':'view_category','PDP':'view_product','SEARCH':'view_search','CHECKOUT|SHIPPING':'init_checkout','CHECKOUT|PAYMENT':'add_payment_info','CHECKOUT|COMPLETE':'purchase'}
if(pageview_events[b.analytics_pagename]){b.vk_products_event=pageview_events[b.analytics_pagename];}else if(pageview_events[b.page_type]){b.vk_products_event=pageview_events[b.page_type];}}
if(a=='link'){var link_events={'ADD TO CART':'add_to_cart','REMOVE FROM CART':'remove_from_cart','ADD TO WISHLIST':'add_to_wishlist','REMOVE FROM WISHLIST':'remove_from_wishlist'}
if(link_events[b.event_name]){b.vk_products_event=link_events[b.event_name];}else{return false;}}
var products_array=[];if(b.product_id){for(var i=0,length1=b.product_id.length;i<length1;i++){products_array.push({'id':b.product_id[i],'price':typeof b.product_price!='undefined'&&b.product_price.length>0?(parseFloat(b.product_price[i])*(typeof b.product_quantity!='undefined'?parseInt(b.product_quantity[i]):1)):''})}}
b.vk_parameters={currency_code:b.currency_code,products:products_array};}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"https://vk.com/js/api/openapi.js"
};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
window.vkAsyncInit=function(){if(typeof VK!='undefined'){VK.Retargeting.Init(u.data.pixel_id)
VK.Retargeting.ProductEvent(u.data.price_list_id,u.data.products_event,u.data.parameters);}}
if(a=='link'){VK.Retargeting.ProductEvent(u.data.price_list_id,u.data.products_event,u.data.parameters);}
u.loader_cb=function(){u.initialized=true;};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":"vk_api_transport"});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("408","adidas.adidasglobal");}catch(error){utag.DB(error);}
